//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ФорвестWhere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведение_заказов
    {
        public int Id_покупки { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public Nullable<int> id_товара { get; set; }
        public string название_доставки { get; set; }
        public string стоимость_доставки { get; set; }
        public string сумма_с_доставкой { get; set; }
    
        public virtual Клиенты_магазина Клиенты_магазина { get; set; }
        public virtual Товары_магазина Товары_магазина { get; set; }
    }
}
