//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ФорвестWhere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты_магазина
    {
        public Клиенты_магазина()
        {
            this.Ведение_заказов = new HashSet<Ведение_заказов>();
        }
    
        public int Id_клиента { get; set; }
        public string ФИО { get; set; }
        public string номер { get; set; }
        public string адрес { get; set; }
        public byte[] фото { get; set; }
        public Nullable<int> id_пользователя { get; set; }
    
        public virtual ICollection<Ведение_заказов> Ведение_заказов { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
