//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ФорвестWhere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары_магазина
    {
        public Товары_магазина()
        {
            this.Ведение_заказов = new HashSet<Ведение_заказов>();
        }
    
        public int Id_товара { get; set; }
        public string название { get; set; }
        public string цена { get; set; }
        public string наличие { get; set; }
        public byte[] фото { get; set; }
    
        public virtual ICollection<Ведение_заказов> Ведение_заказов { get; set; }
    }
}
